@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle

UI -right(0- Controller
UI -down(0- DTO
Controller -right(0- Model
Controller -(0- DTO
DTO -up(0- Model
@enduml