@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor LightGrey
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle
hide empty methods
hide empty attributes
class SensorType{
String type
}
class Sensor{
String name
LocalDateTime startingDate
}
class Readings{
double value
LocalDateTime dateTime
}
class Location{
}
class GeographicalAreaType{
String type
}
class GeographicalArea{
String name
}
class AreaShape{
double length
double width
double height
}
class Address{
String zipCode
}
class House{
}
class Room{
String name
int houseFloor
}
class Dimension{
double length
double width
double height
}
class HouseGrid{
String name
}
class PowerSource{
String name
}
class PowerSourceType{
String type
}
class Device{
String name
boolean isActive
}
ENUM DeviceType{
}

Sensor "1" -"1" SensorType
Sensor "1" - "*" Readings
Sensor "1" - "1" Location

House "1" -- "0..*" Room
House "1" -- "1..*" HouseGrid
House "1" ---- "1" Address
House "1" ---- "1" GeographicalArea

Room "1" --- "1" Dimension
Room "1" --- "0..*" Sensor
Room "1" --- "0..*" Device

PowerSource "1" - "1" PowerSourceType

GeographicalArea "1" - "1" GeographicalAreaType
GeographicalArea "1" - "1" GeographicalArea
GeographicalArea "1" - "1" Location
GeographicalArea "1" - "1" AreaShape
GeographicalArea "1" - "0..*" Sensor

Device "1" - "1" Room
Device "1..*" -- "1" DeviceType

HouseGrid "1" - "1..*" PowerSource
HouseGrid "1" - "0..*" Room


@enduml