@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: getRoomListOfSensorsInARoom
activate UI





@enduml

