@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: GetDevicesInHouseGrid
UI -> Controller: GetHouseGridListToString()
Controller -> House: GetHouseGridListToString()
House -> HouseGridList: GetHouseGridListToString()
UI <-- HouseGridList: GetHouseGridListToString()
User <-- UI: GetHouseGridListToString()

User -> UI: ChooseHouseGrid
UI -> Controller: GetHGNameByHGPosition()
Controller -> House: GetHGNameByHGPosition()
House -> HouseGridList: GetNameByHGPosition()
House <-- HouseGridList: GetNameByHGPosition()
Controller <-- House: GetHGNameByHGPosition()
UI <-- Controller: GetHGNameByHGPosition()

UI -> Controller: GetDeviceListContentNameTypeLocationByHG()
Controller -> House: GetDeviceListContentNameTypeLocationByHG()
House -> HouseGridList: GetHGByPosition()
House <-- HouseGridList: GetHGByPosition()
Controller <-- House: GetDeviceListContentNameTypeLocationByHG()
UI <-- Controller: GetDeviceListContentNameTypeLocationByHG()
User <-- UI: GetDeviceListContentNameTypeLocationByHG()
@enduml