@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: GetListOfDevicesInARoom
activate UI

UI -> Controller: getRoomListContent()
activate Controller
Controller -> House: getRoomListContent()
activate House
House -> RoomList: getRoomListContent()
activate RoomList
UI <-- RoomList: RoomListContent()
deactivate RoomList
deactivate House
deactivate Controller
User <-- UI: RoomListContent


User -> UI: Int Position
UI -> Controller: getRoomName(position)
activate Controller
Controller -> House: getRoomName(position)
activate House
House -> RoomList: getRoomName(position)
activate RoomList
RoomList -> Room: getName()
activate Room
RoomList <-- Room: getName()
deactivate Room
UI <-- RoomList: RoomName(position)
deactivate RoomList
deactivate House
deactivate Controller


UI -> Controller: getDeviceListContent(position)
activate Controller
Controller -> House: getDeviceListContent(position)
activate House
House -> RoomList: getDeviceListContent(position)
activate RoomList
RoomList -> Room: getDeviceListContent(position)
activate Room
Room -> DeviceList: getDeviceListContent(position)
activate DeviceList
DeviceList -> DeviceList: getLength()
DeviceList -> DeviceList: getDeviceList()
DeviceList -> Device: getName()
activate Device
DeviceList <-- Device: Name()
deactivate Device
UI <-- DeviceList: DeviceListContent()
deactivate DeviceList
deactivate Room
deactivate RoomList
deactivate House
deactivate Controller
User <-- UI: DeviceListContent
deactivate UI
@enduml