@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: GetListOfDevicesInARoom
activate UI

UI -> Controller: GetRoomListContent()
activate Controller
Controller -> House: GetRoomListContent()
activate House
House -> RoomList: GetRoomListContent()
activate RoomList
UI <-- RoomList: GetRoomListContent()
deactivate RoomList
deactivate House
deactivate Controller
User <-- UI: GetRoomListContent()



User -> UI: ChooseRoomFromList
UI -> Controller: GetRoomNameByPosition()
activate Controller
Controller -> House: GetRoomNameByPosition()
activate House
House -> RoomList: GetRoomNameByPosition()
activate RoomList
RoomList -> Room: GetName()
activate Room
RoomList <-- Room: GetName()
deactivate Room
UI <-- RoomList: GetRoomNameByPosition()
deactivate RoomList
deactivate House
deactivate Controller
UI -> Controller: GetDeviceListContentOfRoomByPosition()
activate Controller
Controller -> House: GetDeviceListContentOfRoomByPosition()
activate House
House -> RoomList: GetDeviceListContentByPosition ()
activate RoomList
RoomList -> Room: GetDeviceListContent()
activate Room
Room -> DeviceList: GetDeviceListContent()
activate DeviceList
DeviceList -> DeviceList: GetLength()
DeviceList -> DeviceList: GetDeviceList()
DeviceList -> Device: GetName()
activate Device
DeviceList <-- Device: GetName()
deactivate Device
UI <-- DeviceList: GetDeviceListContent()
deactivate DeviceList
deactivate Room
deactivate RoomList
deactivate House
deactivate Controller
User <-- UI: GetDeviceListContent()
deactivate UI
@enduml