@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: ListOfSensorsInARoom
activate UI

UI -> Controller: getRoomListContent()
activate Controller

Controller -> House: getRoomListContent()
activate House

House -> RoomList: getRoomListContent()
activate RoomList

UI <-- RoomList: RoomListContent
deactivate RoomList
deactivate House
deactivate Controller

User <-- UI: RoomListContent


User -> UI: Int Position
UI -> Controller: getRoomName(position)

activate Controller
Controller -> House: getRoomName(position)

activate House
House -> RoomList: getRoomName(position)

activate RoomList
RoomList -> Room: getName()

activate Room
RoomList <-- Room: Name

deactivate Room
UI <-- RoomList: RoomName(position)
deactivate RoomList
deactivate House
deactivate Controller


UI -> Controller: getSensorListContent(position)
activate Controller
Controller -> House: getSensorListContent(position)
activate House
House -> RoomList: getSensorListContent(position)
activate RoomList
RoomList -> Room: getSensorListContent(position)
activate Room
Room -> SensorList: SensorListContent(position)
activate SensorList

SensorList -> SensorList: getLength()
SensorList -> SensorList: getSensorList()
SensorList -> Sensor: getName()
activate Sensor

SensorList <-- Sensor: Name
deactivate Sensor

UI <-- SensorList: SensorListContent
deactivate SensorList
deactivate Room
deactivate RoomList
deactivate House
deactivate Controller

User <-- UI: SensorListContent
deactivate UI



@enduml