@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

actor User
User -> UI: GetNominalPowerOfAGrid
UI -> Controller: checkIfGridListIsEmpty()
Controller -> House: checkIfGridListIsEmpty()
House -> HouseGridList: checkIfGridListIsEmpty()
HouseGridList --> UI: Grid List is not empty
alt successful case
UI->Controller:

@enduml