@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: getNominalPowerRoomsDevices
activate UI
UI -> Controller: listOfHouseGrids()

Controller -> House: listOfHouseGrids()
House -> HouseGridList: listOfHouseGrids()
activate HouseGridList
UI <-- HouseGridList: listOfHouseGrids()
deactivate HouseGridList
User <-- UI: listOfHouseGrids
User -> UI: Int Position (HouseGrid)
UI -> Controller: getHouseGrid (HouseGrid)
activate Controller
Controller -> House: getHouseGrid (HouseGrid)
activate House
House -> HouseGridList: getHouseGrid (HouseGrid)
activate HouseGridList
Controller <-- HouseGridList: getHouseGrid (HouseGrid)
deactivate HouseGridList
UI <-- Controller: getHouseGrid (HouseGrid)
UI -> Controller: getRoomListContent
Controller -> HouseGrid: getRoomListContent
activate HouseGrid
HouseGrid -> RoomList: getRoomListContent
activate RoomList
UI <-- RoomList: getRoomListContent()
deactivate RoomList
User <-- UI: RoomListContent
User -> UI: Int Position (Room)
UI -> Controller: getDeviceList (Room)
Controller -> HouseGrid: getDeviceList (Room)
HouseGrid -> RoomList: getDeviceList (Room)
activate RoomList
RoomList -> Room: getDeviceList (Room)
activate Room
Room -> DeviceList: getDeviceList (Room)
activate DeviceList
UI <-- DeviceList: getDeviceList (Room)
deactivate DeviceList
User <-- UI: DeviceList
User -> UI: Int Position (Device)
UI -> Controller: addMeasurable (Device)
Controller -> MeasurableList: addMeasurable (Device)
activate MeasurableList
UI <-- MeasurableList: addMeasurable (Device)
deactivate MeasurableList
UI -> Controller:  getNominalPower()
Controller -> MeasurableList: getNominalPower()
activate MeasurableList
UI <-- MeasurableList: getNominalPower()
deactivate MeasurableList
User <-- UI: NominalPower
deactivate UI
@enduml