@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

actor User
User -> UI: GetNominalPowerOfAGrid
UI -> Controller: checkIfGridListIsEmpty()
Controller -> House: checkIfGridListIsEmpty()
House -> HouseGridList: checkIfGridListIsEmpty()
HouseGridList --> UI: boolean
UI->Controller: listHouseGrids()
Controller->House:getHouseGridListToString()
House->HouseGridList:getHouseGridListToString()
HouseGridList-->UI: Shows list of house grids available
User->UI: selects house grid int p
UI->Controller: getHouseGridByPosition(p)


@enduml