@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor PowerUserAdministrator
PowerUserAdministrator -> ":UI": GetDevicesInHouseGrid
activate ":UI"
":UI" -> ":Controller": GetHouseGridListToString()
activate ":Controller"
":Controller" -> ":House": GetHouseGridListToString()
activate ":House"
":House" -> ":House": GetHouseGridListToString()
":Controller" <-- ":House": String
deactivate ":House"
":UI" <-- ":Controller": String
deactivate ":Controller"
PowerUserAdministrator <--":UI":String

PowerUserAdministrator -> ":UI": ChooseHouseGrid
":UI" -> ":Controller": GetGridNameByPosition()
activate ":Controller"
":Controller" -> ":House": GetGridNameByPosition()
activate ":House"
":House" -> ":House": GetGridNameByPosition()
":Controller" <-- ":House": String
deactivate ":House"
":UI" <-- ":Controller": String
deactivate ":Controller"


":UI" -> ":Controller": GetDeviceListContentNameTypeLocationByGrid()
activate ":Controller"
":Controller" -> ":House": GetDeviceListContentNameTypeLocationByGrid()
activate ":House"
":House" -> ":House": GetDeviceListContentNameTypeLocationByGrid()
":Controller" <-- ":House": String
deactivate ":House"
":UI" <-- ":Controller": String
deactivate ":Controller"
PowerUserAdministrator <-- ":UI": String
@enduml