@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: GetDevicesInHouseGrid
activate UI
UI -> Controller: GetHouseGridListToString()
activate Controller
Controller -> House: GetHouseGridListToString()
activate House
House -> HouseGridList: GetHouseGridListToString()
activate HouseGridList
UI <-- HouseGridList: HouseGridListToString
deactivate HouseGridList
deactivate House
User <-- UI: HouseGridListToString

User -> UI: ChooseHouseGrid
UI -> Controller: GetHGNameByHGPosition()
Controller -> House: GetHGNameByHGPosition()
activate House
House -> HouseGridList: GetNameByHGPosition()
activate HouseGridList
House <-- HouseGridList: NameByHGPosition
deactivate HouseGridList
Controller <-- House: HGNameByHGPosition
deactivate House
UI <-- Controller: HGNameByHGPosition


UI -> Controller: GetDeviceListContentNameTypeLocationByHG()

Controller -> House: GetDeviceListContentNameTypeLocationByHG()
activate House
House -> HouseGridList: GetHGByPosition()
activate HouseGridList
House <-- HouseGridList: HGByPosition
deactivate HouseGridList
Controller <-- House: DeviceListContentNameTypeLocationByHG
deactivate House
UI <-- Controller: DeviceListContentNameTypeLocationByHG
deactivate Controller
User <-- UI: DeviceListContentNameTypeLocationByHG
@enduml