@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
	}

autonumber
actor UserAdmin
UserAdmin -> ":ListOfDevicesRoom UI": GetListOfDevicesInARoom
activate ":ListOfDevicesRoom UI"
":ListOfDevicesRoom UI" -> ":ListOfDevicesRoom Controller": getRoomListContent()
activate ":ListOfDevicesRoom Controller"
":ListOfDevicesRoom Controller" -> ":House": getRoomListContent()
activate ":House"
":House" -> ":RoomList": getRoomListContent()
activate ":RoomList"
":ListOfDevicesRoom UI" <-- ":RoomList": RoomListContent
deactivate ":RoomList"
deactivate ":House"
deactivate ":ListOfDevicesRoom Controller"
UserAdmin <-- ":ListOfDevicesRoom UI": RoomListContent

UserAdmin -> ":ListOfDevicesRoom UI": Int position: Room
":ListOfDevicesRoom UI" -> ":ListOfDevicesRoom Controller": getRoomName(Room)
activate ":ListOfDevicesRoom Controller"
":ListOfDevicesRoom Controller" -> ":House": getRoomName(Room)
activate ":House"
":House" -> ":RoomList": getRoomName(Room)
activate ":RoomList"
":RoomList" -> ":Room": getName()
activate ":Room"
":RoomList" <-- ":Room": RoomName
deactivate ":Room"
":ListOfDevicesRoom UI" <-- ":RoomList": RoomName
deactivate ":RoomList"
deactivate ":House"
deactivate ":ListOfDevicesRoom Controller"
":ListOfDevicesRoom UI" -> ":ListOfDevicesRoom Controller": getDeviceListContent(Room)
activate ":ListOfDevicesRoom Controller"
":ListOfDevicesRoom Controller" -> ":House": getDeviceListContent(Room)
activate ":House"
":House" -> ":RoomList": getDeviceListContent(Room)
activate ":RoomList"
":RoomList" -> ":Room": getDeviceListContent (Room)
activate ":Room"
":Room" -> ":DeviceList": getDeviceListContent(Room)
activate ":DeviceList"
":DeviceList" -> ":DeviceList": LengthDeviceList
":DeviceList" -> ":DeviceList": DeviceList
":DeviceList" -> ":Device": getName()
activate ":Device"
":DeviceList" <-- ":Device": DeviceName
deactivate ":Device"
":ListOfDevicesRoom UI" <-- ":DeviceList": DeviceListContent
deactivate ":DeviceList"
deactivate ":Room"
deactivate ":RoomList"
deactivate ":House"
deactivate ":ListOfDevicesRoom Controller"
UserAdmin <-- ":ListOfDevicesRoom UI": DeviceListContent
deactivate ":ListOfDevicesRoom UI"
@enduml