@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> UI: ListOfSensorsInARoom
activate UI
UI -> Controller: getRoomListContent()
activate Controller
Controller -> House: getRoomListContent()
activate House
House -> RoomList: getRoomListContent()
activate RoomList
UI <-- RoomList: RoomListContent
deactivate RoomList
deactivate House
deactivate Controller
User <-- UI: RoomListContent


User -> UI: Int position
UI -> Controller: r = getRoomName(position)
activate Controller
Controller -> House: r = getRoomName(position)
activate House
House -> RoomList: r = getRoomName(position)
activate RoomList
RoomList -> "r: Room": r = getName(position)
activate "r: Room"
deactivate "r: Room"
deactivate RoomList
deactivate House
deactivate Controller

UI -> Controller: r = getSensorListContent()
activate Controller
Controller -> House: r = getSensorListContent()
activate House
House -> RoomList: r = getSensorListContent()
activate RoomList
RoomList -> "r: Room": r = getSensorListContent()
activate "r: Room"
"r: Room" -> SensorList: r = getSensorListContent()
activate SensorList
SensorList -> SensorList: LengthSensorList
SensorList -> SensorList: SensorList
SensorList -> Sensor: getName()
activate Sensor

UI <-- Sensor: SensorName
deactivate Sensor
deactivate SensorList
deactivate "r: Room"
deactivate RoomList
deactivate House
deactivate Controller
deactivate UI

@enduml