@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Black
	ParticipantBackgroundColor DeepSkyBlue
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

actor User
User -> UI: GetNominalPowerOfAGrid
UI -> Controller: checkIfGridListIsEmpty()
Controller -> House: checkIfGridListIsEmpty()
House -> HouseGridList: checkIfGridListIsEmpty()
HouseGridList --> UI: boolean
UI->Controller: listHouseGrids()
Controller->House:getHouseGridListToString()
House->HouseGridList:getHouseGridListToString()
HouseGridList-->UI: House Grid List
UI-->User:Shows list of house grids available
User->UI: Selects house grid :int p
UI->Controller: getHouseGridByPosition(p)
Controller->House: getHouseGridByPosition(p)
House->HouseGridList: getHouseGridByPosition(p)
HouseGridList->UI:HouseGrid hg
UI->Controller:getNominalPower();
Controller->HouseGrid:getNominalPower();
HouseGrid-->UI: double nominalPower

@enduml