@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

activate AdminUser
actor AdminUser

AdminUser -> "ui : ImportRoomSensors":1 - Import room sensors
activate "ui : ImportRoomSensors"
"ui : ImportRoomSensors" --> AdminUser: 2 - Ask for the file path
deactivate "ui : ImportRoomSensors"
AdminUser -> "ui : ImportRoomSensors": 3 - File path
activate "ui : ImportRoomSensors"
"ui : ImportRoomSensors" -> "ctrl : ImportRoomSensors\nController": 3.1 - readFile(file, path)
activate "ctrl : ImportRoomSensors\nController"
"ctrl : ImportRoomSensors\nController" -> "reader : Reader": 3.1.1 - createReader(path)
activate "reader : Reader"
"reader : Reader" --> "ctrl : ImportRoomSensors\nController": 3.1.2 - reader
deactivate "reader : Reader"
"ctrl : ImportRoomSensors\nController" -> "reader : Reader": 3.1.3 - readFile(file)
activate "reader : Reader"
ref over "reader : Reader"
readFile
end
"reader : Reader" --> "ctrl : ImportRoomSensors\nController": 3.1.4 - roomSensorDTOs
deactivate "reader : Reader"
"ctrl : ImportRoomSensors\nController" --> "ui : ImportRoomSensors": 3.2 - roomSensorDTOs
deactivate "ctrl : ImportRoomSensors\nController"
"ui : ImportRoomSensors" --> AdminUser: 4 - Ask for confirmation
deactivate "ui : ImportRoomSensors"
AdminUser -> "ui : ImportRoomSensors": 5 - Confirmation received
activate "ui : ImportRoomSensors"
"ui : ImportRoomSensors" -> "ctrl : ImportRoomSensors\nController": 5.1 - importSensorsToRooms()
activate "ctrl : ImportRoomSensors\nController"
loop for each roomSensorDTO
"ctrl : ImportRoomSensors\nController" -> ReadingMapper: 5.1.1 - mapToEntity(roomSensorDTOs)
activate ReadingMapper
ReadingMapper --> "ctrl : ImportRoomSensors\nController": 5.1.2 - RoomSensor sensor
deactivate ReadingMapper
"ctrl : ImportRoomSensors\nController" -> "HouseService": 5.1.3 - addSensorToRoom(roomId,sensor)
activate HouseService
ref over HouseService
addSensorToRoom
end
"HouseService" --> "ctrl : ImportRoomSensors\nController": 5.1.3.1 - true
deactivate HouseService
end loop
"ctrl : ImportRoomSensors\nController" --> "ui : ImportRoomSensors": 5.2 - true
deactivate "ctrl : ImportRoomSensors\nController"
"ui : ImportRoomSensors" --> AdminUser: 6 - Give feedback
deactivate "ui : ImportRoomSensors"
@enduml