@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

actor RegularUser
activate RegularUser
actor RegularUser
RegularUser -> ":GetDayWithHighest\nTemperatureAmplitudeUI": 1- getDayWithHighest\nTemperatureAmplitude
activate ":GetDayWithHighest\nTemperatureAmplitudeUI"

":GetDayWithHighest\nTemperatureAmplitudeUI" --> "RegularUser": 2-Ask for initial date
deactivate ":GetDayWithHighest\nTemperatureAmplitudeUI"
":GetDayWithHighest\nTemperatureAmplitudeUI" <- "RegularUser": 3-Insert initial date
activate ":GetDayWithHighest\nTemperatureAmplitudeUI"
":GetDayWithHighest\nTemperatureAmplitudeUI" --> "RegularUser": 4-Ask for final date
deactivate ":GetDayWithHighest\nTemperatureAmplitudeUI"
":GetDayWithHighest\nTemperatureAmplitudeUI" <- "RegularUser": 5-Insert final date
activate ":GetDayWithHighest\nTemperatureAmplitudeUI"
":GetDayWithHighest\nTemperatureAmplitudeUI" -> ":GetDayWithHighest\nTemperatureAmplitude\nController": 5.1- getDayWithHighest\nTemperatureAmplitude (initial and final date)
activate ":GetDayWithHighest\nTemperatureAmplitude\nController"
":GetDayWithHighest\nTemperatureAmplitude\nController"-> ":House": 5.1.1- getDailyAmplitude\nInIntervalInHouseArea (initial and final date)
activate ":House"
":House" -> ":GeographicalArea": 5.1.1.1- getDailyAmplitudeInInterval (initial and final date)
activate ":GeographicalArea"
ref over ":GeographicalArea"
getDailyAmplitudeInInterval
(initial and final date)
end
":House" <-- ":GeographicalArea": 5.1.1.2- mapOfDailyAmplitude
deactivate ":GeographicalArea"
":GetDayWithHighest\nTemperatureAmplitude\nController"<-- ":House": 5.1.2- mapOfDailyAmplitude
deactivate ":House"
":GetDayWithHighest\nTemperatureAmplitude\nController" -> ":House": 5.1.3- getHighestDailyAmplitude ()
activate ":House"
":House" -> ":GeographicalArea": 5.1.3.1- getHighestDailyAmplitude ()
activate ":GeographicalArea"
":House" <-- ":GeographicalArea": 5.1.3.2- mapOfHighestDailyAmplitude
deactivate ":GeographicalArea"
":GetDayWithHighest\nTemperatureAmplitude\nController" <-- ":House": 5.1.4- mapOfHighestDailyAmplitude
deactivate ":House"
deactivate ":GetDayWithHighest\nTemperatureAmplitude\nController"
":GetDayWithHighest\nTemperatureAmplitudeUI" -> ":GetDayWithHighest\nTemperatureAmplitude\nController": 5.2- displayResults ()
activate ":GetDayWithHighest\nTemperatureAmplitude\nController"
":GetDayWithHighest\nTemperatureAmplitudeUI" <-- ":GetDayWithHighest\nTemperatureAmplitude\nController": 5.3- displayResults
deactivate ":GetDayWithHighest\nTemperatureAmplitude\nController"

RegularUser <-- ":GetDayWithHighest\nTemperatureAmplitudeUI": 6- String Result
deactivate ":GetDayWithHighest\nTemperatureAmplitudeUI"
deactivate RegularUser
@enduml