@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}
autonumber
actor AdminUser
activate AdminUser
actor AdminUser

AdminUser -> ":ConfigureHouseFromAFileUI": configureHouse
activate ":ConfigureHouseFromAFileUI"
AdminUser <-- ":ConfigureHouseFromAFileUI": pathOFileRequest
deactivate ":ConfigureHouseFromAFileUI"
AdminUser -> ":ConfigureHouseFromAFileUI": pathOfFile
activate ":ConfigureHouseFromAFileUI"
":ConfigureHouseFromAFileUI" -> ":ConfigureHouseInformation\nFromJSONOController" :  readFile(file,path)
activate ":ConfigureHouseInformation\nFromJSONOController"
":ConfigureHouseInformation\nFromJSONOController" -> "<<ProjectFileReader>>": readFile()
activate "<<ProjectFileReader>>"
ref over "<<ProjectFileReader>>"
readFile()
end

":ConfigureHouseInformation\nFromJSONOController" <--  "<<ProjectFileReader>>": ListOfHouseObjects
deactivate "<<ProjectFileReader>>"
":ConfigureHouseFromAFileUI" <-- ":ConfigureHouseInformation\nFromJSONOController": ListOfHouseObjects
deactivate ":ConfigureHouseInformation\nFromJSONOController"
AdminUser <-- ":ConfigureHouseFromAFileUI" : contentOfFile + confirmationMessage (Y/N)
deactivate ":ConfigureHouseFromAFileUI"
AdminUser -> ":ConfigureHouseFromAFileUI": confirmationMessage
activate ":ConfigureHouseFromAFileUI"
":ConfigureHouseFromAFileUI" -> ":ConfigureHouseInformation\nFromJSONOController": importHouseInformation()
activate ":ConfigureHouseInformation\nFromJSONOController"
":ConfigureHouseInformation\nFromJSONOController" -> ":HouseService": updateHouseWithRoomsAndGrids()
activate ":HouseService"
":HouseService" -> "AddressMapper" : mapToEntity(address)
activate "AddressMapper"
":HouseService"<-- "AddressMapper" : address
deactivate "AddressMapper"
loop
":HouseService" -> "RoomMapper" :  mapToEntity(room)
activate "RoomMapper"
":HouseService" <-- "RoomMapper" : room
 deactivate "RoomMapper"
 end
 loop
":HouseService" -> "HouseGridMapper" :  mapToEntity(houseGrid)
 activate "HouseGridMapper"
 ":HouseService" <-- "HouseGridMapper" : grid
  deactivate "HouseGridMapper"
  loop for each room
  ":HouseService" -> "grid :HouseGrid" :  addRoom(room)
  activate "grid :HouseGrid"
  ":HouseService" <-- "grid :HouseGrid" : true
  deactivate "grid :HouseGrid"
  end
  end
 ":ConfigureHouseInformation\nFromJSONOController" <-- ":HouseService": true
 deactivate ":HouseService"
 ":ConfigureHouseInformation\nFromJSONOController" <-- ":ConfigureHouseInformation\nFromJSONOController" : writeAddressToFile(address)
":ConfigureHouseFromAFileUI" <-- ":ConfigureHouseInformation\nFromJSONOController": true
 deactivate ":ConfigureHouseInformation\nFromJSONOController"
AdminUser <-- ":ConfigureHouseFromAFileUI": confirmationMessage
deactivate ":ConfigureHouseFromAFileUI"
deactivate AdminUser



@enduml