@startuml

UI "1" -> "1" Controller
UI "1" --> "1" ReadingDTO
ReadingDTO "1" --> "1" ReadingMapper
ReadingMapper "1" --> "1" CSVReader
Controller "1" --> "1" ReadingMapper
ReadingMapper "1" -> "1" GeographicalAreaList
GeographicalAreaList "1" --> "0*" SensorList
SensorList "1" --> "0*" Sensor

Class UI {
-field1
-field2
+method1()
+method2()
}

Class Controller {
-field1
-field2
+method1()
+method2()
}

Class ReadingMapper {
-field1
-field2
+method1()
+method2()
}

Class CSVReader {
-field1
-field2
+method1()
+method2()
}

Class GeographicalAreaList {
-field1
-field2
+method1()
+method2()
}

Class SensorList {
-field1
-field2
+method1()
+method2()
}

Class Sensor {
-field1
-field2
+method1()
+method2()
}

Class ReadingDTO {
-field1
-field2
+method1()
+method2()
}
@enduml