@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

activate AdminUser
actor AdminUser

AdminUser -> ":ImportReadings\nFromCSVUI":1 - Import readings from a CSV file
activate ":ImportReadings\nFromCSVUI"
":ImportReadings\nFromCSVUI" -> ":ImportReadings\nFromCSVController": 1.1 - create()
activate ":ImportReadings\nFromCSVController"
":ImportReadings\nFromCSVController" -> ":GeographicalAreaList": 1.1.1 - create()
activate ":GeographicalAreaList"
":GeographicalAreaList" --> ":ImportReadings\nFromCSVController": 1.1.2 - geoAreaList
deactivate ":GeographicalAreaList"
":ImportReadings\nFromCSVController" -> ":SensorList": 1.2.1 - create()
activate ":SensorList"
":SensorList" --> ":ImportReadings\nFromCSVController": 1.2.2 - sensorList
deactivate ":SensorList"
":ImportReadings\nFromCSVController" --> ":ImportReadings\nFromCSVReaderUI": 1.2 - controller
deactivate ":ImportReadings\nFromCSVController"
":ImportReadings\nFromCSVUI" -> ReadingMapper: 1.3 - newReadingDTO()
activate ReadingMapper

ReadingMapper -> ":ReadingDTO": 1.3.1 - create()
activate ":ReadingDTO"
":ReadingDTO" --> ReadingMapper: 1.3.2 - readingDTO
deactivate ":ReadingDTO"
ReadingMapper --> ":ImportReadings\nFromCSVUI": 1.4 - readingDTO
deactivate ReadingMapper
":ImportReadings\nFromCSVUI" --> AdminUser: 2 - Ask for the file name/path
deactivate ":ImportReadings\nFromCSVUI"
AdminUser -> ":ImportReadings\nFromCSVUI": 3 - Receive file name/path
activate ":ImportReadings\nFromCSVUI"
":ImportReadings\nFromCSVUI" -> ":ImportReadings\nFromCSVUI": 3.1 - checkIfFileExistsAndCreateScanner(path)
loop readLinesAndImportReadings
end loop
":ImportReadings\nFromCSVUI" --> AdminUser: 4 - Give feedback
deactivate



deactivate AdminUser

@enduml