@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

activate ":ImportReadings\nFromCSVUI"
loop readLinesAndImportReadings
":ImportReadings\nFromCSVUI" -> CSVReader: 3.2 - parseLine(line)
activate CSVReader
CSVReader --> ":ImportReadings\nFromCSVUI": 3.3 - sensorId, dateTime, value
deactivate CSVReader
":ImportReadings\nFromCSVUI" -> ":ImportReadings\nFromCSVController": 3.4 - checkIfSensorExistsById(sensorId)
activate ":ImportReadings\nFromCSVController"
":ImportReadings\nFromCSVController" -> ":SensorList": 3.4.1 - checkIfSensorExistsById(sensorId)
activate ":SensorList"
":SensorList" --> ":ImportReadings\nFromCSVController": 3.4.2 - sensor
deactivate ":SensorList"
":ImportReadings\nFromCSVUI" -> ":ImportReadings\nFromCSVController": 3.5 - checkDateTimeAndStoreIt(dateTime)
":ImportReadings\nFromCSVController" -> ":Sensor": 3.5.1 - getStartingDate()
activate ":Sensor"
":Sensor" --> ":ImportReadings\nFromCSVController": 3.5.2 - startingDate
deactivate ":Sensor"
":ImportReadings\nFromCSVController" --> ":ImportReadings\nFromCSVUI": 3.6 - validDateTime
deactivate ":ImportReadings\nFromCSVController"
":ImportReadings\nFromCSVUI" --> ":ImportReadings\nFromCSVUI": 3.7 - checkValueAndStoreIt(value)
":ImportReadings\nFromCSVUI" -> ":ReadingDTO": 3.7 - setDateTime(validDateTime)
":ImportReadings\nFromCSVUI" -> ":ReadingDTO": 3.8 - setValue(validValue)
":ImportReadings\nFromCSVUI" -> ":ImportReadings\nFromCSVController": 3.9 - addReadingToTheSensor(readingDTO)
activate ":ImportReadings\nFromCSVController"
":ImportReadings\nFromCSVController" -> ReadingMapper: 3.9.1 - mapToEntity(readingDTO)
activate ReadingMapper
ReadingMapper --> ":ImportReadings\nFromCSVController": 3.9.2 - reading
deactivate ReadingMapper
":ImportReadings\nFromCSVController" -> ":Sensor": 3.9.3 - addReadingToTheSensor(reading)
deactivate ":ImportReadings\nFromCSVController"
end loop

@enduml
