@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

actor RegularUser
RegularUser -> ":UI":
activate ":UI"
":UI" -> ":Controller":
activate ":Controller"
":Controller" -> ":House":
activate ":House"
":Controller" <-- ":House":
deactivate ":House"
":UI" <-- ":Controller":
deactivate ":Controller"
RegularUser <-- ":UI":
deactivate ":UI"

RegularUser -> ":UI":
activate ":UI"
":UI" -> ":Controller":
activate ":Controller"
":Controller" -> ":House":
activate ":House"
":Controller" <-- ":House":
deactivate ":House"
deactivate ":Controller"

PowerUser -> ":UI":
PowerUser -> ":UI":
":UI" -> ":Controller":
activate ":Controller"
":Controller" -> ":Device":
activate ":Device"
":Controller" <-- ":Device":
deactivate ":Device"
":UI" <-- ":Controller":
deactivate ":Controller"
PowerUser <-- ":UI":
deactivate ":UI"

@enduml