@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

actor User
User -> ":DeleteDevice\nFromRoomUI": 1- DeleteDeviceFromRoom
activate ":DeleteDevice\nFromRoomUI"
":DeleteDevice\nFromRoomUI" -> ":DeleteDeviceFrom\nRoomController": 1.1- getRoomListContent()
activate ":DeleteDeviceFrom\nRoomController"
":DeleteDeviceFrom\nRoomController" -> ":House": 1.1.1- getRoomListContent()
activate ":House"

":DeleteDeviceFrom\nRoomController" <-- ":House": 1.1.2- roomListContent
deactivate ":House"
":DeleteDevice\nFromRoomUI" <-- ":DeleteDeviceFrom\nRoomController": 1.2- roomListContent
deactivate ":DeleteDeviceFrom\nRoomController"
User <-- ":DeleteDevice\nFromRoomUI": 1.3- roomListContent

User -> ":DeleteDevice\nFromRoomUI": 2- Int position: Room
":DeleteDevice\nFromRoomUI" -> ":DeleteDeviceFrom\nRoomController": 2.1- getRoomName(position)
activate ":DeleteDeviceFrom\nRoomController"
":DeleteDeviceFrom\nRoomController" -> ":House": 2.1.1- getRoomName(position)
activate ":House"
":DeleteDeviceFrom\nRoomController" <-- ":House": 2.1.2- roomName
deactivate ":House"
":DeleteDevice\nFromRoomUI" <-- ":DeleteDeviceFrom\nRoomController": 2.2- roomName
deactivate ":DeleteDeviceFrom\nRoomController"


":DeleteDevice\nFromRoomUI" -> ":DeleteDeviceFrom\nRoomController": 2.3- getDeviceListContent(Room)
activate ":DeleteDeviceFrom\nRoomController"
":DeleteDeviceFrom\nRoomController" -> ":House": 2.3.1- getDeviceListContent(Room)
activate ":House"
":House" -> ":RoomList": 2.3.1.1- getDeviceListContent(Room)
activate ":RoomList"
":RoomList" -> ":Room": 2.3.1.1.1- getDeviceListContent (Room)
activate ":Room"
":RoomList" <-- ":Room": 2.3.1.1.2- deviceListContent
deactivate ":Room"
":House" <-- ":RoomList":  2.3.1.2- deviceListContent
deactivate ":RoomList"
":DeleteDeviceFrom\nRoomController" <-- ":House": 2.3.2- deviceListContent
deactivate ":House"
":DeleteDevice\nFromRoomUI" <-- ":DeleteDeviceFrom\nRoomController": 2.4- deviceListContent
deactivate ":DeleteDeviceFrom\nRoomController"
User <-- ":DeleteDevice\nFromRoomUI": 2.5- deviceListContent

User -> ":DeleteDevice\nFromRoomUI": 3- Int position
":DeleteDevice\nFromRoomUI" -> ":DeleteDeviceFrom\nRoomController": 3.1- getDevice(position)
activate ":DeleteDeviceFrom\nRoomController"
":DeleteDeviceFrom\nRoomController" -> ":Room": 3.1.1- getDevice(position)
activate ":Room"
":Room" -> ":DeviceList": 3.1.1.1- getDevice(position)
activate ":DeviceList"
":Room" <-- ":DeviceList": 3.1.1.2- device
deactivate ":DeviceList"
":DeleteDeviceFrom\nRoomController" <-- ":Room": 3.1.2- device
deactivate ":Room"
":DeleteDevice\nFromRoomUI" <-- ":DeleteDeviceFrom\nRoomController": 3.2- device
deactivate ":DeleteDeviceFrom\nRoomController"

User --> User: 4- ConfirmDeletionDevice
":DeleteDevice\nFromRoomUI" --> ":DeleteDeviceFrom\nRoomController": 4.1- deletionDevice()
activate ":DeleteDeviceFrom\nRoomController"
":DeleteDeviceFrom\nRoomController" --> ":Room": 4.1.1- deletionDevice()
activate ":Room"
":Room" --> ":DeviceList": 4.1.1.1- deletionDevice()
activate ":DeviceList"
":Room" <-- ":DeviceList": 4.1.1.2- successMessage
deactivate ":DeviceList"
":DeleteDeviceFrom\nRoomController" <-- ":Room": 4.1.2- successMessage
deactivate ":Room"
":DeleteDevice\nFromRoomUI" <-- ":DeleteDeviceFrom\nRoomController": 4.2- successMessage
deactivate ":DeleteDeviceFrom\nRoomController"
User <-- ":DeleteDevice\nFromRoomUI": 4.3- successMessage
deactivate ":DeleteDevice\nFromRoomUI"

@enduml