@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

actor PowerUser
PowerUser -> ":GetEnergyConsumption\nHouseGridUI": 1- GetEnergyConsumptionOfHouseGrid
activate ":GetEnergyConsumption\nHouseGridUI"
":GetEnergyConsumption\nHouseGridUI" -> ":GetEnergyConsumption\nHouseGridController": 1.1- getHouseGridListToString()
activate ":GetEnergyConsumption\nHouseGridController"
":GetEnergyConsumption\nHouseGridController" -> ":House": 1.1.1- getHouseGridListToString()
activate ":House"
":GetEnergyConsumption\nHouseGridController" <-- ":House": 1.1.2- houseGridList
deactivate ":House"
":GetEnergyConsumption\nHouseGridUI" <-- ":GetEnergyConsumption\nHouseGridController": 1.2- houseGridList
deactivate ":GetEnergyConsumption\nHouseGridController"
PowerUser <-- ":GetEnergyConsumption\nHouseGridUI": 1.3- houseGridList

PowerUser -> ":GetEnergyConsumption\nHouseGridUI": 2- Int House Grid Position
":GetEnergyConsumption\nHouseGridUI" -> ":GetEnergyConsumption\nHouseGridController": 2.1- getHouseGridByPosition(position)
activate ":GetEnergyConsumption\nHouseGridController"
":GetEnergyConsumption\nHouseGridController" -> ":House": 2.2- getHouseGridByPosition (position)
activate ":House"
":GetEnergyConsumption\nHouseGridController" <-- ":House": 2.3- choosenHouseGrid
deactivate ":GetEnergyConsumption\nHouseGridController"
deactivate ":House"

PowerUser <- ":GetEnergyConsumption\nHouseGridUI": 3- Ask for Start Date and End Date

PowerUser -> ":GetEnergyConsumption\nHouseGridUI": 3.1- Insert Start Date (LocalDateTime)
PowerUser -> ":GetEnergyConsumption\nHouseGridUI": 3.2- Insert End Date (LocalDateTime)
":GetEnergyConsumption\nHouseGridUI" -> ":GetEnergyConsumption\nHouseGridController": 3.2.1- GetEnergyConsumption(startDate, endDate)
activate ":GetEnergyConsumption\nHouseGridController"
":GetEnergyConsumption\nHouseGridController" -> ":HouseGrid": 3.2.1.1- GetEnergyConsumption(startDate, endDate)
activate ":HouseGrid"
":GetEnergyConsumption\nHouseGridController" <-- ":HouseGrid": 3.2.1.2- Energy Consumption
deactivate ":HouseGrid"
":GetEnergyConsumption\nHouseGridUI" <-- ":GetEnergyConsumption\nHouseGridController": 3.2.2- energyConsumption
deactivate ":GetEnergyConsumption\nHouseGridController"
PowerUser <-- ":GetEnergyConsumption\nHouseGridUI": 3.3- energyConsumption
deactivate ":GetEnergyConsumption\nHouseGridUI"

@enduml