@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

actor PowerUser
PowerUser -> ":UI": 1- GetEnergyConsumptionOfDevice
activate ":UI"
":UI" -> ":Controller": 1.1- GetAllDevicesToString()
activate ":Controller"
":Controller" -> ":House": 1.2- GetAllDevicesToString()
activate ":House"
":Controller" <-- ":House": 1.3- String
deactivate ":House"
":UI" <-- ":Controller": 1.4- String
PowerUser <-- ":UI": 1.5- String

PowerUser -> ":UI": 2- Int Device Position
":UI" -> ":Controller": 2.1- SetDevice(position)
":Controller" -> ":House": 2.2- GetDeviceByPosition (position)
activate ":House"
":Controller" <-- ":House": 2.3- Device
deactivate ":House"


PowerUser -> ":UI": 3- Insert Start Date (LocalDateTime)
PowerUser -> ":UI": 4- Insert End Date (LocalDateTime)
":UI" -> ":Controller": 4.1- GetEnergyConsumption(startDate, endDate)
":Controller" -> ":Device": 4.2- GetEnergyConsumption(startDate, endDate)
activate ":Device"
":Controller" <-- ":Device": 4.3- double
deactivate ":Device"
":UI" <-- ":Controller": 4.4- double
PowerUser <-- ":UI": 4.5- double
deactivate ":UI"

@enduml