@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle
DeactivateSensorFromGeoAreaUI "1" -right-> "1" DeactivateSensorFromGeoAreaController
DeactivateSensorFromGeoAreaController "1" -right-> "1" GeographicalAreaList
GeographicalArea "1" --> "1" SensorList
GeographicalAreaList "1" --> "*" GeographicalArea
DeactivateSensorFromGeoAreaController --> GeographicalAreaMapper: uses

GeographicalAreaMapper -left-> GeographicalAreaDTO : creates
DeactivateSensorFromGeoAreaUI "1"--> "*" GeographicalAreaDTO
SensorList "1" -left-> "*" Sensor
GeographicalAreaDTO "1" -down-> "*" SensorDTO

Class DeactivateSensorFromGeoAreaUI {
-controller: DeactivateSensorFromGeoAreaController
+run()
+deactivateSensor()
+printListOfGeoAreas()
+printListOfSensors()
}

Class DeactivateSensorFromGeoAreaController {
-geographicalAreaList: GeographicalAreaList
+listOfGeographicalAreas()
+deactivateSensor()
}

Class GeographicalAreaMapper{
+mapToDTO(GeographicalArea)
}

Class GeographicalAreaList {
-geoAreaList: List<GeographicalArea>
+getGeoAreaById()
}

Class GeographicalArea {
-id: String
-geoAreaSensorList: SensorList
+getSensorList()
+removeSensor()
}

Class SensorList {
-listOfSensors: List<Sensor>
+getSensorById()
}

Class Sensor{
+deactivateSensor()
}

Class GeographicalAreaDTO{
-List<SensorDTO>
+getSensors()
+getId()
}

@enduml