@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}
activate "ctrl : DeactivateSensor\nFromGeoArea\nController"
"ctrl : DeactivateSensor\nFromGeoArea\nController" -> GeographicalArea: getGeoAreaList()

loop GeographicalArea

"GeographicalArea" -> "LocationMapper": mapToDTO(latitude,longitude,altitude)
activate "GeographicalArea"
activate "LocationMapper"
"LocationMapper" --> "GeographicalArea": locationDTO
deactivate GeographicalArea
deactivate "LocationMapper"
"GeographicalArea" -> "GeographicalAreaMapper": mapToDTO(id,description,\ntype,width,legth,locationDTO)
activate GeographicalArea
activate "GeographicalAreaMapper"
"GeographicalAreaMapper" -> ":GeographicalAreaDTO" :  create
activate ":GeographicalAreaDTO"
":GeographicalAreaDTO" --> "GeographicalAreaMapper": geographicalAreaDTO
deactivate ":GeographicalAreaDTO"

loop SensorList
"SensorList" -> "LocationMapper": mapToDTO(latitude,longitude,altitude)
activate "LocationMapper"
"LocationMapper" --> "SensorList": locationDTO
deactivate "LocationMapper"
"SensorList" -> ":SensorDTO": newSensorDTO()
activate ":SensorDTO"
":SensorDTO" --> "SensorList": sensorDTO
deactivate ":SensorDTO"
"SensorList" -> ":GeographicalAreaDTO" : addSensorDTO
end
end
"GeographicalAreaMapper" --> "ctrl : DeactivateSensor\nFromGeoArea\nController" :DTOList
deactivate GeographicalArea
deactivate "GeographicalAreaMapper"



@enduml