@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

loop GeographicalAreaList
activate "GeographicalAreaList"
"GeographicalAreaList" -> "LocationMapper": mapToDTO(latitude,longitude,altitude)
activate "LocationMapper"
"LocationMapper" --> "GeographicalAreaList": locationDTO
deactivate "LocationMapper"
"GeographicalAreaList" -> "GeographicalAreaMapper": mapToDTO(id,description,\ntype,width,legth,locationDTO)
activate "GeographicalAreaMapper"
"GeographicalAreaMapper" -> ":GeographicalAreaDTO" :  create
activate ":GeographicalAreaDTO"
":GeographicalAreaDTO" --> "GeographicalAreaMapper": geographicalAreaDTO
deactivate ":GeographicalAreaDTO"

"GeographicalAreaMapper" --> "GeographicalAreaList": geographicalAreaDTO
deactivate "GeographicalAreaMapper"

loop parseSensor
"GeographicalAreaList" -> "LocationMapper": mapToDTO(latitude,longitude,altitude)
activate "LocationMapper"
"LocationMapper" --> "GeographicalAreaList": locationDTO
deactivate "LocationMapper"
"GeographicalAreaList" -> ":SensorDTO": newSensorDTO()
activate ":SensorDTO"
":SensorDTO" --> "GeographicalAreaList": sensorDTO
deactivate ":SensorDTO"
"GeographicalAreaList" -> ":GeographicalAreaDTO" : addSensorDTO

end
end
@enduml