@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber
actor User
User -> Ui: GetNominalPowerOfARoom
Ui -> Controller: GetListOfRooms
Controller -> House: GetListOfRooms

House -> RoomList: getRoomFromAPosition
Ui <-- RoomList: Room list

User -> Ui: Choose room from list
Ui -> Controller: CheckIfDeviceListIsEmpty
Controller -> House: CheckIfDeviceListIsEmpty
House -> RoomList: CheckIfDeviceListIsEmpty
RoomList -> Room: CheckIfDeviceListIsEmpty
Room -> DeviceList: CheckIfDeviceListIsEmpty
Controller <-- DeviceList: boolean


Controller -> House: getNominalPowerOfARoom
House -> RoomList: getNominalPowerOfARoom
RoomList -> Room: getNominalPowerOfARoom
Ui <-- Room: NominalPowerOfARoom
User <-- Ui: double NominalPowerOfARoom
@enduml