@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
    ArrowColor Black
    ActorBorderColor DarkBlue
    LifeLineBorderColor black
    LifeLineBackgroundColor LightGrey

    ParticipantBorderColor Black
    ParticipantBackgroundColor LightGrey
    ParticipantFontStyle Bold

    ActorBackgroundColor DimGrey
    ActorFontColor DeepSkyBlue
    ActorFontStyle Bold
    ActorFontSize 17
    ActorFontName Aapex
}

activate ":GetFirst\nHottestDay\nHouseAreaUI"
":GetFirst\nHottestDay\nHouseAreaUI" -> ":GetFirst\nHottestDay\nHouseArea\nController": 1- checkNearestSensor\nReadingExistence\nBetweenDates
activate ":GetFirst\nHottestDay\nHouseArea\nController"
":GetFirst\nHottestDay\nHouseArea\nController" -> ":House": 1.1- checkNearestSensor\nReadingExistence\nBetweenDates
activate ":House"
":House" -> ":GeographicalArea": 1.1.1- getNearestSensor\nWithTheMost\nRecentReading
activate ":GeographicalArea"
":GeographicalArea" --> ":House": 1.1.2- Sensor
deactivate ":GeographicalArea"
":House" -> ":Sensor": 1.2.1- checkMeasurement\nExistanceBetweenDates
activate ":Sensor"
":Sensor" --> ":GetFirst\nHottestDay\nHouseAreaUI": 1.2.2- boolean
deactivate ":Sensor"

deactivate ":House"
deactivate ":GetFirst\nHottestDay\nHouseArea\nController"
deactivate ":GetFirst\nHottestDay\nHouseAreaUI"

@enduml