@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

actor RegularUser
activate RegularUser
RegularUser -> ":GetFirst\nHottestDay\nHouseAreaUI": 1- getDayWithHighest\nTemperature
activate ":GetFirst\nHottestDay\nHouseAreaUI"
":GetFirst\nHottestDay\nHouseAreaUI" -> ":GetFirst\nHottestDay\nHouseArea\nController":
activate ":GetFirst\nHottestDay\nHouseArea\nController"
":GetFirst\nHottestDay\nHouseArea\nController" -> ":House":
activate ":House"
":GetFirst\nHottestDay\nHouseArea\nController" <-- ":House":
deactivate ":House"
":GetFirst\nHottestDay\nHouseAreaUI" <-- ":GetFirst\nHottestDay\nHouseArea\nController":
deactivate ":GetFirst\nHottestDay\nHouseArea\nController"
RegularUser <-- ":GetFirst\nHottestDay\nHouseArea\nController":
deactivate ":GetFirst\nHottestDay\nHouseArea\nController"


@enduml