@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
    ArrowColor Black
    ActorBorderColor DarkBlue
    LifeLineBorderColor black
    LifeLineBackgroundColor LightGrey

    ParticipantBorderColor Black
    ParticipantBackgroundColor LightGrey
    ParticipantFontStyle Bold

    ActorBackgroundColor DimGrey
    ActorFontColor DeepSkyBlue
    ActorFontStyle Bold
    ActorFontSize 17
    ActorFontName Aapex
}

actor RegularUser
activate RegularUser
RegularUser -> ":GetFirst\nHottestDay\nHouseAreaUI": 1- getDayWithHighest\nTemperature
ref over ":GetFirst\nHottestDay\nHouseAreaUI"
checkIfThereAreTemperatureSensors
end
activate ":GetFirst\nHottestDay\nHouseAreaUI"



":GetFirst\nHottestDay\nHouseAreaUI" --> "RegularUser": 6-Insert Initial Date
deactivate ":GetFirst\nHottestDay\nHouseAreaUI"
":GetFirst\nHottestDay\nHouseAreaUI" <- "RegularUser": 6-Initial Date
activate ":GetFirst\nHottestDay\nHouseAreaUI"
":GetFirst\nHottestDay\nHouseAreaUI" --> "RegularUser": 6-Insert Final Date
deactivate ":GetFirst\nHottestDay\nHouseAreaUI"
":GetFirst\nHottestDay\nHouseAreaUI" <- "RegularUser": 6-Final Date
activate ":GetFirst\nHottestDay\nHouseAreaUI"
ref over ":GetFirst\nHottestDay\nHouseAreaUI"
checkIfThereAreReadings
end
":GetFirst\nHottestDay\nHouseAreaUI" -> ":GetFirst\nHottestDay\nHouseArea\nController": getFirstHighestReadingHouseArea
activate ":GetFirst\nHottestDay\nHouseArea\nController"
":GetFirst\nHottestDay\nHouseArea\nController" -> ":House": getFirstHighestReadingHouseArea
activate ":House"
":House" ->":GeographicalArea": getFirstHighestReading
activate ":GeographicalArea"
ref over ":GeographicalArea"
getLatestReadingFromNearestSensor
end

":GeographicalArea" --> ":GetFirst\nHottestDay\nHouseArea\nController" :Reading
deactivate ":GeographicalArea"
deactivate ":House"
":GetFirst\nHottestDay\nHouseArea\nController" ->"ReadingMapper": mapToDTO(sensor)
activate "ReadingMapper"
"ReadingMapper" -> ":ReadingDTO": create ReadingDTO
activate ":ReadingDTO"
":ReadingDTO" --> ":GetFirst\nHottestDay\nHouseAreaUI": ReadingDTO
deactivate ":ReadingDTO"

deactivate "ReadingMapper"
deactivate ":GetFirst\nHottestDay\nHouseArea\nController"


":GetFirst\nHottestDay\nHouseAreaUI" --> ":GetFirst\nHottestDay\nHouseAreaUI" : getDTOValue
":GetFirst\nHottestDay\nHouseAreaUI" --> ":GetFirst\nHottestDay\nHouseAreaUI" : getDTODateTime

":GetFirst\nHottestDay\nHouseAreaUI" --> RegularUser : display first hottest \n day and it's value
deactivate ":GetFirst\nHottestDay\nHouseAreaUI"

@enduml