@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle

GetLastColdestDayHouseArea\nUI "1" -> "1" GetLastColdestDayHouseArea\nController
GetLastColdestDayHouseArea\nController "1" --> "1" House
House "1" -> "1" GeographicalArea : directly inserted in
GeographicalArea "1" -> "1" SensorList
SensorList "1" --> "0*" Sensor
Sensor "1" -up-> "0*" Reading
ReadingMapper "1" --> "1" Reading : MapsToDTO
GetLastColdestDayHouseArea\nController  "1" -> "1" ReadingMapper  : uses
ReadingMapper "1" -right-> "1" ReadingDTO

Class GetLastColdestDayHouseArea\nUI {
-GetLastColdestDayHouseAreaController\n controller
-ReadingDTO readingDTO
-LocalDate firstDate
-LocalDate lastDate
+run()
+askAndValidateFirstAndLastDate()
+getLastColdestDayReadingAndDisplayResults()
+displayResults()
}

Class GetLastColdestDayHouseArea\nController {
- House house;
- SensorType sensorTypeTemperature;
+hasSensorsOfGivenTypeInGeoArea()
+hasReadingsBetweenDates()
+getLastLowestMaximumReading()
}

Class House {
-GeographicalArea insertedGeoArea
-Address address
+hasSensorsOfGivenTypeInGeoArea()
+getNearestSensorWithMostRecentReading()
+getLastLowestMaximumReading()
}

Class GeographicalArea {
-SensorList sensorList
-Location location
+getTheSensorListOfAGivenType()
+getSensorsInGeographicalAreaByType()
+getNearestSensorWithMostRecentReading()
+getLastLowestMaximumReading()
}

Class SensorList {
-List<Sensor> listOfSensors
+getNearestSensorsToLocation()
+getSensorWithMostRecentReading()
}

Class Sensor {
-List<Reading> listOfReadings
-SensorType sensorType
-Location location
+checkMeasurementExistenceBetweenDates()
+getSensorType()
+getSensorWithMostRecentReading()
+distanceBetweenSensorAndLocation()
+getMeasurementValueBetweenDates()
+getHighestReadingOfADay()
+getDailyMaxReadingsInAnInterval()
+getLastLowestReading()
}

Class Reading {
-double value
-LocalDateTime dateTime
+getValue()
+getDateTime()
}

Class ReadingMapper{
+newReadingDTO()
+mapToDTO()
}

Class ReadingDTO{
-double value;
-LocalDateTime dateTime;
+getValue()
+setValue()
+getDateTime()
+setDateTime()
}

@enduml