@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle

UI "1" -> "1" GetLastColdestDayHouseArea\nController
GetLastColdestDayHouseArea\nController "1" --> "1" House
House "1" -> "1" GeographicalArea : directly inserted in
GeographicalArea "1" -> "1" SensorList
SensorList "1" --> "0*" Sensor
Sensor "1" --> "0*" Reading
ReadingMapper --> Reading
GetLastColdestDayHouseArea\nController --> ReadingMapper

Class UI {
-GetLastColdestDayHouseAreaController\n controller
-ReadingDTO readingDTO
-LocalDate firstDate
-LocalDate lastDate
+run()
+getFirstAndLastDate()
+displayResults()
}

Class GetLastColdestDayHouseArea\nController {
- House house;
- SensorType sensorTypeTemperature;
+hasSensorsOfCertainTypeInInsertedGeoArea()
+hasReadingsBetweenDates()
+getLastLowestMaximumReading()
}

Class House {
-GeographicalArea insertedGeoArea
-Address address
+hasSensorsOfCertainTypeInInsertedGeoArea(
+getNearestSensorWithMostRecentReading()
+getLastLowestMaximumReading()
}

Class GeographicalArea {
-SensorList sensorList
-Location location
+getTheSensorListOfAGivenType()
+getSensorsInGeographicalAreaByType()
+getNearestSensorWithMostRecentReading()
+getLastLowestMaximumReading()
}

Class SensorList {
-List<Sensor> listOfSensors
+getNearestSensorsToLocation()
+getSensorWithMostRecentReading()
}

Class Sensor {
-List<Reading> listOfReadings
-SensorType sensorType
-Location location
+checkMeasurementExistenceBetweenDates()
+getSensorType()
+getSensorWithMostRecentReading()
+distanceBetweenSensorAndLocation()
+getMeasurementValueBetweenDates()
+getHighestReadingOfADay()
+getDailyMaxReadingsInAnInterval()
+getLastLowestReading()
}

Class Reading {
-double value
-LocalDateTime dateTime
+getValue()
+getDateTime()
}

Class ReadingMapper{
+newReadingDTO()
+mapToDTO()
}

@enduml