@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
   ArrowColor Black
   ActorBorderColor DarkBlue
   LifeLineBorderColor black
   LifeLineBackgroundColor LightGrey

   ParticipantBorderColor Black
   ParticipantBackgroundColor LightGrey
   ParticipantFontStyle Bold

   ActorBackgroundColor DimGrey
   ActorFontColor DeepSkyBlue
   ActorFontStyle Bold
   ActorFontSize 17
   ActorFontName Aapex
}
activate ":GeographicalArea"
":GeographicalArea" ->":SensorList": 1- getNearestSensorWithTheMostRecentReading(sensorType,location)
activate ":SensorList"
":SensorList" --> ":GeographicalArea": 2- sensor
deactivate ":SensorList"
":GeographicalArea" -> ":Sensor":3- getLastLowestMaximumReading(startDate,endDate)
activate ":Sensor"
loop getLastLowestReading
":Sensor" -> ":Readings": 3.1- getDailyMaxReadingsInAnInterval(startDate,endDate)
activate ":Readings"
end
":Readings" --> ":Sensor" :3.2- lastLowestReading
deactivate ":Readings"

":Sensor" --> ":GeographicalArea": 4- lastLowestReading
deactivate ":Sensor"
deactivate ":GeographicalArea"

@enduml