@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

activate RegularUser
actor RegularUser
RegularUser -> ":GetLastColdestDay\nHouseAreaUI":
activate ":GetLastColdestDay\nHouseAreaUI"
":GetLastColdestDay\nHouseAreaUI" -> ":GetLastColdestDay\nHouseAreaController":
activate ":GetLastColdestDay\nHouseAreaController"
":GetLastColdestDay\nHouseAreaController" -> ":House":
activate ":House"
":GetLastColdestDay\nHouseAreaController" <-- ":House":
deactivate ":House"
":GetLastColdestDay\nHouseAreaUI" <-- ":GetLastColdestDay\nHouseAreaController":
deactivate ":GetLastColdestDay\nHouseAreaController"
RegularUser <-- ":GetLastColdestDay\nHouseAreaUI":
deactivate ":GetLastColdestDay\nHouseAreaUI"

RegularUser -> ":GetLastColdestDay\nHouseAreaUI":
activate ":GetLastColdestDay\nHouseAreaUI"
":GetLastColdestDay\nHouseAreaUI" -> ":GetLastColdestDay\nHouseAreaController":
activate ":GetLastColdestDay\nHouseAreaController"
":Controller" -> ":House":
activate ":House"
":Controller" <-- ":House":
deactivate ":House"
deactivate ":GetLastColdestDay\nHouseAreaController"

PowerUser -> ":GetLastColdestDay\nHouseAreaUI":
PowerUser -> ":GetLastColdestDay\nHouseAreaUI":
":GetLastColdestDay\nHouseAreaUI" -> ":GetLastColdestDay\nHouseAreaController":
activate ":GetLastColdestDay\nHouseAreaController"
":GetLastColdestDay\nHouseAreaController" -> ":Device":
activate ":Device"
":GetLastColdestDay\nHouseAreaController" <-- ":Device":
deactivate ":Device"
":GetLastColdestDay\nHouseAreaUI" <-- ":GetLastColdestDay\nHouseAreaController":
deactivate ":GetLastColdestDay\nHouseAreaController"
PowerUser <-- ":GetLastColdestDay\nHouseAreaUI":
deactivate ":GetLastColdestDay\nHouseAreaUI"

deactivate RegularUser


@enduml