@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle

ImportGeoAreasFromJSONUI "1" --> "1" ImportGeoAreasFromJSONController
ImportGeoAreasFromJSONController  "1" -left-> "1" GeographicalAreaList
ImportGeoAreasFromJSONController  "1" --> "1" GeographicalAreaMapper
ImportGeoAreasFromJSONController  "1" --> "1" GeographicalAreaDTO
ImportGeoAreasFromJSONController  "1" --> "1" SensorDTO
ImportGeoAreasFromJSONController  "1" --> "1" SensorMapper
ImportGeoAreasFromJSONController  "1" -right-> "1" JSONReader

Class ImportGeoAreasFromJSONUI {
-ImportGeoAreasFromJSONController controller
+run()

}

Class ImportGeoAreasFromJSONController {
-geographicalAreaList
+importGeographicalAreasAndSensors()
}

Class GeographicalAreaMapper {
+mapToDTO()
+mapToEntity(geographicalAreaDTO)
}

Class GeographicalAreaList {
-List <GeographicalArea> geoAreaList
+addGeoArea(geographicalArea)
}

Class GeographicalAreaDTO {
- String id
- String name
- String type
- double width
- double length
- double latitude
- double altitude
- double longitude
- List <SensorDTO> sensor
+ get()
+ set()
+ addSensor()
}

Class SensorDTO {
- String id
- String name
- String type
- LocalDate startingDate
- LocationDTO location
- String units
+ get()
+ set()
}

Class SensorMapper {

+newSensorDTO()
+entityToMap()
+mapToEntity()
}

Class JSONReader {
+ readJSONFileToList()
}

@enduml