@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}

activate ":SensorsService"
":SensorsService" -> ":RoomSensorService": getRoomReadingsDTO(startDate, endDate, roomSensorId)
activate ":RoomSensorService"
":RoomSensorService" -> ":RoomSensorRepo": getSensorById(sensorId)
activate ":RoomSensorRepo"
":RoomSensorService" <-- ":RoomSensorRepo": S
deactivate ":RoomSensorRepo"
":RoomSensorService" -> "S: RoomSensor": getReadings(startDate, endDate)
"S: RoomSensor" -> "S: RoomSensor": getReadings(startDate, endDate)
deactivate ":RoomSensorRepo"
":RoomSensorService" <-- "S: RoomSensor": readingsList
deactivate "S: RoomSensor"
":RoomSensorService" -> ":RoomSensorService": getReadingsDTO(readingsList)
":SensorsService" <-- ":RoomSensorService": readingDTOList
deactivate ":SensorsService"


@enduml