@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}
autonumber

activate ":SensorsService"
":SensorsService" -> ":RoomSensorService": getRoomReadingsDTO\n(startDate, endDate, sensorId)
activate ":RoomSensorService"
":RoomSensorService" -> ":RoomSensor": getReadingsDTO\n(startDate, endDate, sensorId)
activate ":RoomSensor"
":RoomSensorService" -> ":RoomSensorRepo":getSensorById(sensorId)
activate ":RoomSensorRepo"
":RoomSensorService" <-- ":RoomSensorRepo": Sensor
deactivate ":RoomSensorRepo"
":RoomSensor" -> ":RoomSensor": getReadings(startDate, endDate)
deactivate ":RoomSensorRepo"
":RoomSensorService" <-- ":RoomSensor": List<Readings>
deactivate ":RoomSensor"
":SensorsService" <-- ":RoomSensorService": List<ReadingDTO>
deactivate ":RoomSensorService"
deactivate ":SensorsService"


@enduml