@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle
GeographicalAreaList "." -right-> "." "<<Service>>\nGeoAreaService": uses
"<<Service>>\nGeoAreaService" "1" -right-> "1" "<<Repository>>\nGeoAreaRepository"
GeographicalAreaList --> "<<Entity>>\nGeographicalArea"
"<<Entity>>\nGeographicalArea" -right-> "<<Entity>>\nSensor"
"<<Entity>>\nSensor" -right-> "<<Entity>>\nReading"

Class "<<Service>>\nGeoAreaService" {
- static GeoAreaService
+getInstance()
+getGeoAreaRepository()
+setGeoAreaRepository()
}

Class GeographicalAreaList {
-List<GeographicalArea> geoAreaList
+addGeoArea()
+updateRepository()
}

Class "<<Entity>>\nGeographicalArea" {
-String id
-String description
-GeographicalAreaType geographicalAreaType
-GeographicalArea insertedIn
-Location location
-AreaShape areaShape
}

Class "<<Entity>>\nSensor" {
-String id
-String sensorName
-LocalDateTime startingDate
-SensorType sensortype
-Location location
-String units
-boolean isActive
}

Class "<<Entity>>\nReading" {
-Long id
-double value
-LocalDateTime date
}


Interface "<<Repository>>\nGeoAreaRepository"{
}

@enduml