@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle
"<<Entity>>\nHouseGrid" "." -right-> "." "<<Service>>\nHouseService": uses
"<<Service>>\nHouseService" "1" -down-> "1" "<<Repository>>\nRoomRepository"
"<<Service>>\nHouseService" "1" -right-> "1" "<<Repository>>\nHouseGridRepository"
"<<Entity>>\nRoom" "1" -down-> "0 .. *" "<<Entity>>\nRoomSensor"
"<<Entity>>\nRoomSensor" "1" -right-> "0 .. *" "Reading"
"<<Entity>>\nRoom" "." -left-> "." "<<Service>>\nHouseService": uses
"<<Entity>>\nRoom" "1"-left-> "1" "HouseGridId"
"<<Entity>>\nHouseGrid" "1" -down-> "1" "HouseGridId"



Class "HouseGridId" {
- String houseGridId
+ getHouseGridId()
}


Class "<<Service>>\nHouseService" {
- RoomRepository
- HouseGridRepository
+ updateHouseWithRoomsAndGrids()
}

Class "<<Entity>>\nHouseGrid" {
- HouseGridId houseGridId
+ addGeoArea()
+ updateRepository()
}

Class "<<Entity>>\nRoom" {
- RoomId id
- String description
- int houseFloor
- Dimension dimension
}

Class "<<Entity>>\nRoomSensor" {
- String id
- String sensorName
- LocalDateTime startingDate
- SensorType sensortype
- String units
}

Class "Reading" {
- Long id
- double value
- LocalDateTime date
}

hide empty attributes
hide empty methods
Interface "<<Repository>>\nRoomRepository"{

}

Interface "<<Repository>>\nHouseGridRepository"{
}

@enduml