@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
    ArrowColor Black
    ActorBorderColor DarkBlue
    LifeLineBorderColor black
    LifeLineBackgroundColor LightGrey

    ParticipantBorderColor Black
    ParticipantBackgroundColor LightGrey
    ParticipantFontStyle Bold

    ActorBackgroundColor DimGrey
    ActorFontColor DeepSkyBlue
    ActorFontStyle Bold
    ActorFontSize 17
    ActorFontName Aapex
}
autonumber
":GeographicalAreaList" -> "geoAreaService\n:GeoAreaService": getInstance()
activate ":GeographicalAreaList"
activate "geoAreaService\n:GeoAreaService"
":GeographicalAreaList"  <-- "geoAreaService\n:GeoAreaService":geoAreaService
deactivate "geoAreaService\n:GeoAreaService"
deactivate ":GeographicalAreaList"

":GeographicalAreaList" -> "geoAreaService\n:GeoAreaService": getGeoAreaRepository()
activate ":GeographicalAreaList"
activate "geoAreaService\n:GeoAreaService"
":GeographicalAreaList"  <-- "geoAreaService\n:GeoAreaService":geoAreaRepository
deactivate "geoAreaService\n:GeoAreaService"
deactivate ":GeographicalAreaList"
":GeographicalAreaList" -> "geoAreaRepository\n:GeoAreaRepository": save(geoArea)
activate ":GeographicalAreaList"
activate "geoAreaRepository\n:GeoAreaRepository"

@enduml