@startuml

UI "1" -> "1" Controller
Controller "1" --> "1" House
House "1" -> "1" GeographicalArea : directly inserted in
GeographicalArea "1" -> "1" SensorList
SensorList "1" --> "0*" Sensor
Sensor "1" --> "0*" Reading

Class UI {
-field1
-field2
+method1()
+method2()
}

Class Controller {
-field1
-field2
+method1()
+method2()
}

Class House {
-field1
-field2
+method1()
+method2()
}

Class GeographicalArea {
-field1
-field2
+method1()
+method2()
}

Class SensorList {
-field1
-field2
+method1()
+method2()
}

Class Sensor {
-field1
-field2
+method1()
+method2()
}

Class Reading {
-field1
-field2
+method1()
+method2()
}

@enduml