@startuml
skinparam linetype ortho

skinparam class {
	BackgroundColor PaleTurquoise
	ArrowColor Black
	BorderColor Black
	FontStyle Bold
}

hide circle

UI "1" --> "1" Controller
Controller "1" --> "1" GeographicalAreaList
Controller "1" --> "1" GeographicalAreaMapper
Controller "1" --> "1" GeographicalAreaDTO
Controller "1" --> "1" SensorDTO
Controller "1" --> "1" SensorMapper
Controller "1" --> "1" JSONReader

Class UI {
-field1
-field2
+method1()
+method2()
}

Class Controller {
-field1
-field2
+method1()
+method2()
}

Class GeographicalAreaMapper {
-field1
-field2
+method1()
+method2()
}

Class GeographicalAreaList {
-field1
-field2
+method1()
+method2()
}

Class GeographicalAreaDTO {
-field1
-field2
+method1()
+method2()
}

Class SensorDTO {
-field1
-field2
+method1()
+method2()
}

Class SensorMapper {
-field1
-field2
+method1()
+method2()
}

Class JSONReader {
-field1
-field2
+method1()
+method2()
}

@enduml