@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}
actor AdminUser
activate AdminUser
actor AdminUser

AdminUser -> ":ImportReadings\nFromJSONUI": 1- importReadingsFromJSON
activate ":ImportReadings\nFromJSONUI"
AdminUser <-- ":ImportReadings\nFromJSONUI": 2- pathOfJsonFileRequest
deactivate ":ImportReadings\nFromJSONUI"
AdminUser -> ":ImportReadings\nFromJSONUI": 3- pathOfJSONFile
activate ":ImportReadings\nFromJSONUI"
":ImportReadings\nFromJSONUI" -> ":JSONReader" : 3.1- readJSONFileToList (reader)
activate ":JSONReader"
":ImportReadings\nFromJSONUI" <-- ":JSONReader" : 3.2- ListOfGeographicalAreasDTO
deactivate ":JSONReader"
AdminUser <-- ":ImportReadings\nFromJSONUI": 4- contentOfFile + confirmationMessage (Y/N)
deactivate ":ImportReadings\nFromJSONUI"
AdminUser -> ":ImportReadings\nFromJSONUI": 5- confirmationMessage
activate ":ImportReadings\nFromJSONUI"
":ImportReadings\nFromJSONUI" -> ":ImportReadings\nFromJSONController": 5.1-importGeographicalAreasAndSensors\n(listOfGeoAreasDTO)
activate ":ImportReadings\nFromJSONController"
":ImportReadings\nFromJSONController" -> "GeographicalAreaMapper" : 5.1.1- mapToEntity(geographicalAreaDTO)
activate "GeographicalAreaMapper"
"GeographicalAreaMapper" -> ":GeographicalArea" : 5.1.1.1- createGeographicalArea()
activate ":GeographicalArea"
"GeographicalAreaMapper" <-- ":GeographicalArea" : 5.1.1.2- geographicalArea
deactivate ":GeographicalArea"
":ImportReadings\nFromJSONController" <-- "GeographicalAreaMapper" : 5.1.2- geographicalArea
deactivate "GeographicalAreaMapper"
":ImportReadings\nFromJSONController" -> "SensorMapper" : 5.1.3- mapToEntity(sensor)
activate "SensorMapper"
"SensorMapper" -> ":Sensor" : 5.1.3.1- createSensor()
activate ":Sensor"
"SensorMapper" <-- ":Sensor" : 5.1.3.2- sensor
deactivate ":Sensor"
":ImportReadings\nFromJSONController" <-- "SensorMapper" : 5.1.4- sensor
 deactivate "SensorMapper"
":ImportReadings\nFromJSONController"  -> ":GeographicalAreaList" : 5.1.5- AddGeographicalArea(geographicalArea)
activate ":GeographicalAreaList"
":ImportReadings\nFromJSONController" <-- ":GeographicalAreaList" : 5.1.6- boolean
deactivate ":GeographicalAreaList"
":ImportReadings\nFromJSONUI" <-- ":ImportReadings\nFromJSONController": 5.2- boolean
deactivate ":ImportReadings\nFromJSONController"
AdminUser <-- ":ImportReadings\nFromJSONUI": 6- confirmationMessage
deactivate ":ImportReadings\nFromJSONUI"
deactivate AdminUser

@enduml