@startuml
skinparam sequenceMessageAlign center
skinparam sequence {
	ArrowColor Black
	ActorBorderColor DarkBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor LightGrey

	ParticipantBorderColor Black
	ParticipantBackgroundColor LightGrey
	ParticipantFontStyle Bold

	ActorBackgroundColor DimGrey
	ActorFontColor DeepSkyBlue
	ActorFontStyle Bold
	ActorFontSize 17
	ActorFontName Aapex
}
activate AdminUser
actor AdminUser

AdminUser -> ":UI":
activate ":UI"
":UI" -> ":Controller":
activate ":Controller"
":Controller" -> ":House":
activate ":House"
":Controller" <-- ":House":
deactivate ":House"
":UI" <-- ":Controller":
deactivate ":Controller"
AdminUser <-- ":UI":
deactivate ":UI"

AdminUser-> ":UI":
activate ":UI"
":UI" -> ":Controller":
activate ":Controller"
":Controller" -> ":House":
activate ":House"
":Controller" <-- ":House":
deactivate ":House"
deactivate ":Controller"

AdminUser -> ":UI":
AdminUser-> ":UI":
":UI" -> ":Controller":
activate ":Controller"
":Controller" -> ":Device":
activate ":Device"
":Controller" <-- ":Device":
deactivate ":Device"
":UI" <-- ":Controller":
deactivate ":Controller"
AdminUser <-- ":UI":
deactivate ":UI"

deactivate AdminUser

@enduml